onedr0p/cluster-template

README.md
Fixed wrong export name in README file
=> [FIX] Flux Export Name In README.md

README.md
https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
Not sure if this was a recent change, but I wasn't able to create a cert without using these permissions for the api token.
[cert-manager-cert-manager-5fb4bf49bf-cx7jp-1627409159255032807.log](https://github.com/k8s-at-home/template-cluster-k3s/files/6889604/cert-manager-cert-manager-5fb4bf49bf-cx7jp-1627409159255032807.log)
=> docs: Update Cloudflare API key permissions

cluster/core/system-upgrade/kustomization.yaml
Updates the system-upgrade-controller kustomization to pull from the source repo's root kustomization.yaml instead of the release yaml. Also brings system-upgrade-controller up to v0.7.3
**Benefits**
This allows renovate bot to update the controller automatically.
=> update system-upgrade to repo root kustomziation

cluster/core/cert-manager/kustomization.yaml, cluster/core/cert-manager/secret.enc.yaml
I was following the README instructions and run into a problem where flux would fail because of a `cloudflare-token-secret` secret that was created without the data set. My understanding is that `secret.enc.yaml` was renamed to`secret.sops.yaml`, but not every configuration was updated accordingly.
=> fix: remove duplicate secret definition, update kustomization.yaml

cluster/apps/networking/traefik/helm-release.yaml
This option allows the use of service type `ExternalName`:
https://kubernetes.io/docs/concepts/services-networking/service/#externalname
**Benefits**
One can create `ExternalName` service
=> Allow ExternalName services

cluster/apps/default/hajimari/helm-release.yaml, cluster/apps/networking/traefik/dashboard/ingress.yaml
PR switches go global substring replacement for domain in TLS secret name.
**Benefits**
Allows use of subdomains in SECRET DOMAIN. For example, my cluster uses a domain like `subdomain.domain.tld`.
Prior to this fix, secrets were created with format:
`subdomain-domain.tld-tls`
After this fix, secrets created are of form:
`subdomain-domain-tld-tls`
See "Substring Replacement" in these docs as a reference
https://tldp.org/LDP/abs/html/string-manipulation.html 
May break existing deployments? Not sure.
- fixes #
=> Use global substring substitution for tls secret

.envrc, README.md, Taskfile.yml, provision/ansible/playbooks/k3s-install.yml
Signed-off-by: Devin Buhl <devin.kray@gmail.com>
Places the kubeconfig into the provision dir
**Benefits**
Buck is not confused
`whereis kubeconfig`
- fixes #
=> feat: move kubeconfig to provision folder during ansible k3s-install

configure.sh, tmpl/cluster/kube-vip-daemonset.yaml
After following the setup guide and running `./configure.sh`, I encountered two pre-commit yamllint errors when trying to commit the generated files:
```sh
$ git commit
yamllint....................................................................Failed
- hook id: yamllint
- exit code: 1
cluster/core/kube-system/kube-vip/daemon-set.yaml
47:15     error    wrong indentation: expected 16 but found 14  (indentation)
provision/ansible/inventory/hosts.yml
1:1       warning  missing document start "---"  (document-start)
```
**Benefits**
Easier setup, less problems for first time users.
No drawbacks.
However, considering you can define list elements in yaml with and without indentation:
```sh
list:
- a
- b
```
vs.
```sh
list:
- a
- b
```
... …
=> Fix pre-commit yammlint errors during setup

provision/ansible/requirements.yml
Added ansible.posix collection to the ansible requirements file. The ubuntu-prepare playbook was crashing on the filesystem task due to the missing collection, required to create the max user watches sysctl config file.
=> fix: add ansible.posix collection to requirements

.config.sample.env, .envrc, .gitignore, README.md, cluster/base/apps.yaml, cluster/base/core.yaml, configure.sh, tmpl/.sops.yaml, tmpl/cluster/gotk-sync.yaml
Signed-off-by: Devin Buhl <devin@buhl.casa>
Use age instead of gpg
**Benefits**
Age is easier to configure and use, Flux also mentions in their documentation to use this over GPG when you are able to.
- fixes #152 
To migrate from GPG to Age:
- Create age public / private key:
```sh
age-keygen -o age.agekey
mkdir -p ~/.config/sops/age
mv age.agekey ~/.config/sops/age/keys.txt
export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt
source ~/.bashrc
```
- Decrypt all secrets (e.g. `find ./cluster -type f -iname "*sops*" -exec sops --decrypt --in-place {} \;`
- Update `.sops.yaml` with age public key and remove pgp keys.
- Encrypt all secrets with age (e.g. `find ./cluster -type f -iname …
=> feat: use age instead of gpg for sops

cluster/apps/system-upgrade/system-upgrade-controller/agent-plan.yaml, cluster/apps/system-upgrade/system-upgrade-controller/server-plan.yaml
Currently the ansible k3s role installs version v1.22.3+k3s1, but the system-upgrade controller is using the v1.21 channels.
This causes downgrade problems.
**Benefits**
Version matches 
none
none
none
=> match system-upgrade channels to deployed k3s ver

README.md
age-secret is not needed in the "default" namespace. This secret is needed in the "flux-system" namespace.
**Benefits**
secret can be used correctly 
none
none
none
=> fix age-secret namespace

README.md
Add `--kubeconfig=./provision/kubeconfig` option to sops/flux integration command.
**Benefits**
Return code 0!
None that I know.
=> fix(readme.md): Add ./provision/kubeconfig to sops/flux setup.

provision/ansible/playbooks/templates/kube-vip-daemonset.yaml.j2, tmpl/cluster/kube-vip-daemonset.yaml
Drops SYS_TIME capability
**Benefits**
Less permissions for the container to manipulate the host
- fixes #
Dropped upstream in https://github.com/kube-vip/kube-vip/pull/336
=> kube-vip: Drop SYS_TIME capability

README.md
This PR updates the readme to fix the README typo regarding which files are encrypted by SOPS.
**Benefits**
Clearer README instructions
None, if the README correction is accurate
- fixes: https://github.com/k8s-at-home/template-cluster-k3s/issues/176#issuecomment-1002817502
New to this repo so hope I got the fix right 😄
=> chore: fix typo regarding sops files in readme

provision/ansible/roles/ubuntu/tasks/packages.yml
Add two tasks to determine if the role is running on a raspberry pi and install raspi specific packages.
Currently only package linux-modules-extra-raspi
**Benefits**
Calico pods will start successfully. Without the package the pods had periodic sigvaults every 30 secs. All other pods coulnt be deployed
Only tested on raspi 4
=> WIP: add specific packages for raspberry pi on Ubuntu 21.01

provision/ansible/playbooks/templates/kube-vip-daemonset.yaml.j2
Bump to kube-vip 0.4.2 in ansible playbooks to keep in sync with what's deployed later through flux.
**Benefits**
- fixes #
=> ansible/templates: Bump to kube-vip 0.4.2

.github/renovate.json5
Looks like https://github.com/k8s-at-home/template-cluster-k3s/pull/272 doesn't include the ansible template. Hopefully this change will help updating this one as well.
=> fix: Update kube-vip on ansible template as well

provision/ansible/inventory/group_vars/kubernetes/k3s.yml
This should allow to update the k3s version used to install automatically.
v1.23.5+k3s1 is released, so if it works we should see a PR coming for that.
=> fix: Add k3s release to renovate

README.md
The first step in the Ansible part of the guide mentions you should ensure you are able to SSH into your nodes from your workstation using your private SSH key. I simply added a link to a guide that describes how to generate a ssh key, add it to your server and disable password based logon.
**Benefits**
Easy reference / cheatsheet for those unfamiliar with the setup process.
N/A
N/A
N/A
=> chore: add guide for configuring SSH key auth

provision/terraform/cloudflare/main.tf
Change the minimum TLS version from 1.0 to 1.2 on the Cloudflare side
**Benefits**
Improved security by dropping support for insecure / deprecated TLS versions
None that I see currently, please correct me if I'm wrong
N/A
<https://www.venafi.com/blog/why-its-dangerous-use-outdated-tls-security-protocols>
<https://www.packetlabs.net/posts/tls-1-1-no-longer-secure/>
=> fix(cloudflare): min TLS version 1.0 -> 1.2

.config.sample.env, README.md, configure.sh, tmpl/cluster/flux-system/kustomization.yaml, tmpl/cluster/flux-system/webhooks/github/ingress.yaml, tmpl/cluster/flux-system/webhooks/github/kustomization.yaml, tmpl/cluster/flux-system/webhooks/github/receiver.yaml, tmpl/cluster/flux-system/webhooks/github/secret.sops.yaml, tmpl/cluster/flux-system/webhooks/kustomization.yaml
Adds manifest for setting up Flux receiver for Github webhooks and instructions how to set it up from the Github side
**Benefits**
Easy set-up for Github webhooks for new and existing users
Added dependency on yq and another variable to configure
N/A
N/A
=> Add templates and logic to set up manifests for Github webhook receiver

.config.sample.env, configure
Add an option to disable kube-vip
**Benefits**
Reduced resource usage on clusters that don't have a HA control plane.
This mainly allows to not disable kube-vip because of limitations when exposing a kubernetes api endpoint via wireguard (layer3 tunnel, so ARP won't work there).
=> Add option to disable kube-vip

.github/workflows/lint.yaml
`superlinter` has an obsolete version of `kubeval`, which makes it fail every PR issued by `renovate`.
I have opened an issue with superlinter here but am not sure how fast it'll get fixed: https://github.com/github/super-linter/issues/3181
Example of failing workflow: https://github.com/mrtolkien/cluster/runs/7552734767?check_suite_focus=true
**Benefits**
PR issued by `renovate` won't fail for users of the template, as well as on new customisations. Also, most repos found in `k8s-at-home` use `megalinter` as well.
Superlinter is more popular and maintained by github directly.
=> Moving from super to megalinter 🧹

cluster/charts/kustomization.yaml
Added missing --- of which pre-hooks complained about.
```
cluster/charts/kustomization.yaml
1:1       warning  missing document start "---"  (document-start)
```
**Benefits**
Cleaner template, and no more warnings by default.
None
None
None
=> Update charts kustomization.yaml

provision/ansible/requirements.yml
at the moment v3.3.0 of  `xanmanning.k3s` seems to be unavailable  see more details here: https://github.com/PyratLabs/ansible-role-k3s/issues/196 as such I would suggest considering this workaround. if/when that issue is resolved, this can be reversed.
**Benefits**
- fixes #
=> workaround for ansible galaxy role

cluster/apps/networking/metallb/config.yaml, cluster/apps/networking/metallb/helm-release.yaml, cluster/apps/networking/metallb/kustomization.yaml, cluster/crds/kustomization.yaml, cluster/crds/metallb/crds.yaml, cluster/crds/metallb/kustomization.yaml
Adds CRDs for metlalb
Adds a config file for metallb that creases the address pool off of the same variable it was created from before.
Updates metallb to latest v0.13.5
**Benefits**
Allows updating to the latest version without any drastic changes
Adds a crd - Can't confirm I did it perfectly, can only confirm that it works in this configuration without any issue.
Code blatantly stolen from [Belak](https://github.com/belak/homelab-infra/blob/ebe71636a1a16b32667b09a6337eff24b554ee3e/cluster/bootstrap/crds/metallb-crds.yaml)
- Fixes #409
- Fixes #394 
=> fix(metallb): Update to version with CRDs

cluster/apps/default/hajimari/helm-release.yaml
Hajimari has moved to Helm Release v2.0.2 which contains API updates required for clusters running k8s >1.22.
The Hajimari dev also updated the syntax needed to display bookmarks in groups
**Benefits**
Hajimari will deploy successfully
None that I know of.
=> Update Hajimari HR and Bookmarks syntax

README.md, provision/ansible/inventory/group_vars/kubernetes/os.yml, provision/ansible/playbooks/cluster-prepare.yml
Picking up https://github.com/onedr0p/flux-cluster-template/pull/527 and https://github.com/onedr0p/flux-cluster-template/issues/389
Adding support for Ubuntu
**Benefits**
More choice for users on the OS layer
More maintenance (thus calling it out as  limited community support)
I added the requested changes from https://github.com/onedr0p/flux-cluster-template/pull/527#pullrequestreview-1190466271
To do:
=> Add Support back for Ubuntu as OS

provision/ansible/inventory/group_vars/kubernetes/k3s.yml, provision/ansible/inventory/group_vars/kubernetes/os.yml, provision/ansible/playbooks/cluster-installation.yml, provision/ansible/requirements.yml
- Install Prometheus CRDs on cluster bootstrap
- Wait for custom deployed resources to come exist before deleting the custom manifests
The resource check just verifys that the resources exist, not that they are healthy. That could be improved upon in the future.
Also worth noting that it will wait for the resources to exist but will give up after awhile and **not** error. That is not very UX friendly and also needs to be improved upon.
=> feat: add resource readiness check to cluster-installation playbook

.github/renovate/autoMerge.json5
This change allows automerging any GitHub action types. For example the way we are doing our mdbook action, that would otherwise not get automerged.
=> ci(renovate): Enhance GHA automerge

ansible/playbooks/cluster-prepare.yml
if `kube-vip` cannot find ipvs kernel modules, it will crash-loop with errors (see https://github.com/kube-vip/kube-vip/issues/506)
```txt
level=error msg="ensure IPVS kernel modules are loaded"
level=fatal msg="Error starting IPVS [netlink receive: no such file or directory]"
```
This PR loads `ip_vs` and `ip_vs_rr` and enables them at boot.
Signed-off-by: ahgraber <ahgraber@ninerealmlabs.com>
=> add ipvs kernel modules for kube-vip

ansible/inventory/group_vars/master/k3s.yml, ansible/inventory/group_vars/worker/k3s.yml
Figured I'd submit a diff for the changes asked about here https://discord.com/channels/673534664354430999/740607531466096640/1071641086889562132
This change sets the K3s Agent `kubelet-arg` config setting to an empty value, which prevents K3s from using the `/etc/resolv.conf` file on the host to seed the same file in pods. In my case, I wanted to avoid `search` domains from my cluster nodes' `resolv.conf` files making their way into my pods.
=> Default to empty `resolv-conf` kubelet arg in agent config

kubernetes/apps/networking/metallb/app/helmrelease.yaml
It was removed in chart version 0.13.7:
https://github.com/metallb/metallb/commit/85f3f0c79d3bde54509148c8f09894f016623991
=> fix(metallb): remove psp

ansible/inventory/group_vars/master/k3s.yml, ansible/inventory/group_vars/worker/k3s.yml
Looks like there's an issue including this with coredns crashing
Reverts onedr0p/flux-cluster-template#627
=> Revert "Default to empty `resolv-conf` kubelet arg in agent config"

.github/workflows/meta-labeler.yaml
Since February 2021 Pull Requests created by Dependabot/Renovabot are treated as forks, for reducing attack surface. [[1]](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/)
Which causes some workflows, like labeler to fail due to lack of permissions. This PR fixes that. [[2]](https://github.com/actions/labeler/pull/50)
=> fix(github-action): update permissions on actions/labeler

ansible/inventory/group_vars/kubernetes/k3s.yml, ansible/inventory/group_vars/master/k3s.yml, ansible/playbooks/templates/calico-ebpf.yaml.j2, ansible/playbooks/templates/calico-installation.yaml.j2
Calico supports the eBPF dataplane in more modern distributions like Ubuntu 20.04 and Fedora and newer.
I have been running Calico in eBPF for awhile now and it's been very stable. I follow the docs [here](https://docs.tigera.io/calico/latest/operations/ebpf/enabling-ebpf) and I am just integrating it into the template.
For anyone looking to migrate over, read the [docs](https://docs.tigera.io/calico/latest/operations/ebpf/enabling-ebpf) and the changes in this PR. You might need to reboot your cluster afterwords.
Feedback is appreciated.
=> feat: Disable kube-proxy and enable Calico in eBPF mode

kubernetes/apps/cert-manager/cert-manager/app/kustomization.yaml
The old cert-manager-dashboard json link is no longer working, throwing the error:
```
loading KV pairs: file sources: [cert-manager-dashboard.json=https://raw.githubusercontent.com/monitoring-mixins/website/master/assets/cert-manager/dashboards/cert-manager.json]: URL is a git repository
```
Updated link retrieved from: https://github.com/monitoring-mixins/website/blob/93ac7720f3315fbd77bf169861b1fed4c691d255/mixins.json#L100
=> Update cert-manager-dashboard mixin link

ansible/playbooks/templates/custom-cilium-helmchart.yaml.j2, kubernetes/apps/kube-system/cilium/app/helmrelease.yaml
This changes the ipam from `cluster-pool` to kubernetes, which I tested in my own cluster based off this templet.
This also removes the `operator: enabled` as it's set to true in the helm chart.
=> fix: change Cilium IPAM mode to kubernetes

README.md, kubernetes/apps/networking/ingress-nginx/app/helmrelease.yaml
If an application was throwing any error that is in this list, it forwarded that error to the default backend. A lot of 405 requests where POST requests which gave an 500 error, this resulting in the default backend to handle those requests, but that only accepts GET request, thus transforming the errors in 405. So in reality the real errors where masked, and the applications couldn't handle the error properly resulting in more issues.
=> fix: remove error pages and default backend

.taskfiles/AnsibleTasks.yml
Removing Ansible `task ansible:rollout-reboot` since it's no longer in use, and the playbook was removed in [this commit](https://github.com/onedr0p/flux-cluster-template/commit/4b9b69eb41601d3389d42c377f47f6498b7a0e5f).
=> Remove AnsibleTask no longer in use

configure
The kubeControllerManager endpoints were being cleared on each iteration of the loop over control nodes leading to only the last control node being added. Instead the array should be cleared outside of the loop.
=> Fix setup_prometheus_endpoints in configure

.taskfiles/ClusterTasks.yml
`xargs -L1` is equivalent and compatible with all platforms to `xargs -l` which is only gnu xargs specific. 
`xargs -l` is equivalent to `xargs -L1`
=> Update xargs argument in cluster tasks

ansible/playbooks/cluster-prepare.yml
Simple change that checks if ufw is installed and/or running before attempting to disable it with Ansible.
This fixes the playbook running against Debian machines, which although is not supported, is a good change to have nonetheless.
=> Check if ufw is installed before attempting to disable it

kubernetes/apps/networking/metallb/app/helmrelease.yaml
Disables frr by default. 
Enabled by default: https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml#L321
=> fix(metallb): Disable frr by default

kubernetes/apps/kube-system/cilium/app/helmrelease.yaml
This change will add the cilium icon to hubble-ui inside hajimari, since by default it is the default application icon.
=> fix: Add hubble-ui hajimari icon

template/defaults/templates.yaml
```
[WARNING]: Unable to parse /home/Rodent/home-ops/ansible/inventory/hosts.yaml as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
task: Failed to run task "ansible:list": exit status 1
```
=> fix: Update hosts.yaml destination

Taskfile.yaml
When running the new `task:init` os OSX, I get the following error:
```
$ task init
task: [init] cp --no-clobber vars/addons.sample.yaml vars/addons.yaml
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file target_file
cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file ... target_directory
task: Failed to run task "init": exit status 64
$
```
The `--no-clobber` option is non-POSIX, but GNU-specific. `-n` should work the same in Linux and OSX.
=> Fix `cp` command on OSX

.taskfiles/BrewTasks.yaml
yq is used in the README, when pulling Flux webhook token
=> fix: brew deps - install yq

README.md, requirements.txt
This adds extra steps for Raspberry Pi setup based on recent experience (ansible failing on a fresh Deb12 RPi installation)
This also adds the `jmespath` package to the local .venv requirements, as it's required for `rollout-update`
=> Feat: add package and additional comments required

.github/labeler.yaml, .github/labels.yaml
Labeler currently does not reflect the new folder structure, so everything will just be labeled `area/bootstrap`
=> fix: change labeler to match new directory structure

bootstrap/templates/addons/kubernetes-dashboard/app/helmrelease.yaml.j2, bootstrap/templates/addons/weave-gitops/app/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/kube-system/cilium/app/helmrelease.yaml.j2
Updated ingress className in HelmReleases for `cilium`, `kubernetes-dashboard` and `weave-gitops` so that their URLs resolve.
=> update ingress classNames in HelmReleases

bootstrap/templates/kubernetes/apps/networking/cloudflared/app/configs/config.yaml.j2
As per title, these should be renamed to external instead of the old ingress
=> fix(cloudflared): fixed origin server name

README.md
The plan is to make this a subheading under a new section to be called something like **"Usage: GitOps with Flux, Renovate and GitHub Actions"**.
=> update renovate section of README

README.md, bootstrap/tasks/validation/net.yaml, bootstrap/tasks/validation/vars.yaml, bootstrap/templates/kubernetes/apps/networking/nginx/external/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/networking/nginx/internal/helmrelease.yaml.j2, bootstrap/vars/config.sample.yaml
This is more a cosmetic change, renaming internal/external nginx to internal/external ingress to have technology agnostic variables.
=> Rename internal/external nginx to ingress

bootstrap/templates/addons/kubernetes-dashboard/app/helmrelease.yaml.j2
According to [this issue](https://github.com/kubernetes/dashboard/issues/8191), 7.x is not stable, but the helm chart was published as if it were. They since manually yanked the 7.x versions, causing deployment errors with this chart. This reverts the version to stable 6.x.
=> fix: kubernetes-dashboard version 7.x.x was yanked from the helm repo

bootstrap/tasks/validation/github.yaml, bootstrap/tasks/validation/vars.yaml, bootstrap/templates/kubernetes/flux/config/cluster.yaml.j2, bootstrap/vars/config.sample.yaml
The Flux GitRepository kind allows for configuring the branch reference. Currently, the value is fixed at 'main' in the 'flux-cluster-template' project. This pull request allows configuring the desired branch to be used in the GitRepository manifest.
The code has been tested with different values for the variable `bootstrap_github_repository_branch` and the results were correct. Let me know if you need this results.
=> feat(ansible): add branch reference as variable in gitrepository

bootstrap/templates/ansible/inventory/group_vars/master/main.yaml.j2
Noticed this when using it to deploy dual-stack cluster.
=> fix(ansible/ipv6): Cluster and Service CIDRs didin't get populated for v6

.github/workflows/flux-diff.yaml
If you want to use the flux-diff workflow on a private home-ops repository the added permission is needed. If it is not given the `Diff Resources` step would fail on `Fetching the repository` with the following error message: 
```
remote: Repository not found.
Error: fatal: repository 'https://github.com/janpfischer/home-ops/' not found
```
Adding this permission allows the job to read the content of the private repo. For public repo's this should not make any difference.
=> Adding permission to read repo on flux-diff workflow (mandatory for private repos)

bootstrap/templates/ansible/playbooks/cluster-prepare.yaml.j2
I did _not_ test this against a system that _does_ have apparmor installed, but I _think_ this should work.
=> fix: #990 don't disable apparmor unless it's installed

bootstrap/templates/kubernetes/apps/networking/echo-server/app/helmrelease.yaml.j2
The app-template chart v2 removes `ingressClassName` in favor of `className`, ingress creation breaks if the former is left in place. 
This is the only file I caught using the app template and specifying the ingress, but it caught me out when I was upgrading to 2.0.3
=> Fix echo-server template ingress className

bootstrap/templates/kubernetes/apps/networking/nginx/external/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/networking/nginx/internal/helmrelease.yaml.j2
nginx instances were not following topology Constraints due to mismatching labels. They chose to be together and fall when the node fell. :)
=> Fixed: topology for ingress-nginx instances due to labels not matching

bootstrap/templates/addons/system-upgrade-controller/app/helmrelease.yaml.j2, bootstrap/templates/ansible/playbooks/cluster-prepare.yaml.j2
During a ground up rebuild I noticed that the System Upgrade Controller deployment failed because it could not mount /etc/pki on the host. so I created a task in cluster-prepare.yaml to do so.
```
MountVolume.SetUp failed for volume "etc-pki" : hostPath type check failed: /etc/pki is not a directory
```
=> System Upgrade Controller install failed due to missing /etc/pki dir

.devcontainer/devcontainer.json
Changed a lot from my setup but I think I got all the current recommended client deps. Could be a default devcontainer that supports the initial bootstrap or maybe it makes more sense as an addon?
=> Add first attempt at devcontainer

bootstrap/templates/ansible/playbooks/cluster-prepare.yaml.j2
When trying to run the Ansible node preparation script after the first run, below error gets thrown because Ansible is trying to remove the immutable flag AND delete the file at the same time (apparently it's not smart enough to do the attributes first). By adding an additional step to nuke the immutable attribute, this allows the preparation script to be run multiple times. Also includes some minor lints for Ansible style in that same Jinja2 file.
```
TASK [Network Configuration | Stop systemd-resolved] *****************************************************************************************************************
changed: [k3s-master-0]
changed: [k3s-worker-2]
changed: [k3s-worker-1]
changed: [k3s-worker-0]
TASK [Network Configuration | Remove /etc/resolv.conf] …
```
=> [bootstrap] fix: remove conflicting condition for immutable flag and state:absent

bootstrap/templates/ansible/playbooks/cluster-installation.yaml.j2, bootstrap/templates/ansible/playbooks/cluster-nuke.yaml.j2, bootstrap/templates/ansible/playbooks/cluster-prepare.yaml.j2, bootstrap/templates/ansible/playbooks/cluster-reboot.yaml.j2, bootstrap/templates/ansible/playbooks/cluster-rollout-update.yaml.j2
Based on template's Ansible inventory, all k8s nodes are under `kubernetes` inventory group. In my use case, I've also got a proxmox I want to manage so targeting `all` isn't appropriate. This PR changes the `hosts: all` for cluster node plays to target `kubernetes` appropriately, allowing folks to extend their hosts file as needed.
=> [bootstrap] feat: target cluster ansible plays only to kubernetes in case other hosts are used

bootstrap/tasks/validation/vars.yaml
The variable validation task would always evaluate to true as the assert module seems to just be treating the variable names as strings.
Now we check that the variable exist in the `vars` object and it is defined.
=> [bootstrap] fix: fixed required variable validation assertion

README.md
Noted a slight oopsiedoodle in the Home DNS resolution section referring to `echo-server` to test internal DNS resolution via dns conditional forwarding. We have Cilium's Hubble as an internal ingress so that should do the job just fine. Clarify that any `internal` class ingress would work too, if folks have added additional apps/services.
=> [readme] specify an actual internal ingress for conditional DNS forwarding test

bootstrap/tasks/validation/vars.yaml
Reverts onedr0p/flux-cluster-template#1074
I made a mistake on testing this PR. 
The Jinja `default()` filter does not play nice with boolean variables. Any false-y variables ( e.g. `bootstrap_ipv6_enabled: false` ) will fail the assertion.
Without setting the default filters `boolean` paramater to `true`  the filters scope is limited strictly to `Undefined` which Ansible does not seem to assign to variables that are... undefined. 
```python
def do_default(value, default_value=u'', boolean=False):
"""If the value is undefined it will return the passed default value,
otherwise the value of the variable:
.. sourcecode:: jinja
{{ my_variable|default('my_variable is not defined') }}
This will output the value of ``my_variable`` if the variable was
defined, otherwise ``'my_variable is not …
```
=> Revert "[bootstrap] fix: fixed required variable validation assertion"

bootstrap/tasks/validation/vars.yaml
Turns out it was much simpler than I originally thought.
- `item in vars` checks that the variable exists in the `vars` object
- `vars[item] != None` checks that the variable is set
Empty variables are assigned as `null` by Ansible which Python then translates into `None`.
=> [bootstrap] fix: Fixed required variable validation assertions

.devcontainer/devcontainer.json
In [Stage 3](https://github.com/onedr0p/flux-cluster-template?tab=readme-ov-file#-stage-3-do-bootstrap-configuration) of the README file, we create the key file as `age.key`, but in `SOPS_AGE_KEY_FILE` env variable of the dev container its defined with a preceding dot. This PR fixes this inconsistency (which makes command using the key fail).
=> Fix SOPS_AGE_KEY_FILE env variable in dev container

.devcontainer/devcontainer.json
This PR adds direnv to dev container, but doesn't properly fix #1106 (we still need to hook it to the shell ourselves). I'm just adding it to get some feedback from direnv feature maintainers.
=> Add direnv to dev container definition

bootstrap/templates/addons/homepage/app/helmrelease.yaml.j2
Just running default widgets causes the container to get OOM killed. Bumping up to more reasonable limits.
=> fix: Bump Homepage Memory Req & Limit

bootstrap/templates/ansible/k3s/playbooks/tasks/cruft.yaml.j2
=> I found minor spelling errors

bootstrap/templates/.sops.yaml.j2, bootstrap/templates/ansible/inventory/group_vars/kubernetes/supplemental.yaml.j2, bootstrap/templates/ansible/inventory/hosts.yaml.j2, bootstrap/templates/ansible/playbooks/cluster-nuke.yaml.j2, bootstrap/templates/ansible/playbooks/templates/custom-cilium-helmchart.yaml.j2.j2, bootstrap/templates/k0s-config.yaml.j2, bootstrap/templates/kubernetes/apps/cert-manager/cert-manager/issuers/secret.sops.yaml.j2, bootstrap/templates/kubernetes/apps/default/discord-template-notifier/app/secret.sops.yaml.j2, bootstrap/templates/kubernetes/apps/default/homepage/app/secret.sops.yaml.j2, bootstrap/templates/kubernetes/apps/flux-system/addons/webhooks/github/secret.sops.yaml.j2, bootstrap/templates/kubernetes/apps/flux-system/weave-gitops/app/secret.sops.yaml.j2, bootstrap/templates/kubernetes/apps/kube-system/cilium/app/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/network/cloudflared/app/secret.sops.yaml.j2, bootstrap/templates/kubernetes/apps/network/external-dns/app/secret.sops.yaml.j2, bootstrap/templates/kubernetes/apps/network/k8s-gateway/app/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/network/nginx/external/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/network/nginx/internal/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/observability/grafana/app/secret.sops.yaml.j2, bootstrap/templates/kubernetes/apps/observability/kube-prometheus-stack/app/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/storage/csi-driver-nfs/app/storageclass.yaml.j2, bootstrap/templates/kubernetes/apps/storage/openebs/app/helmrelease.yaml.j2, bootstrap/templates/kubernetes/flux/config/cluster.yaml.j2, bootstrap/templates/kubernetes/flux/vars/cluster-secrets.sops.yaml.j2, bootstrap/templates/kubernetes/flux/vars/cluster-settings.yaml.j2, makejinja.toml
Changes Jinja var start/end delimiters from `{% ... %}` to `#{ ... }#` and comment delimiters to `#| ... |#` for consistency with block delimiters
Hopefully this will be the last change to these delimiters
=> feat: change jinja variable start/end delimiters to avoid conflicts with go templating

bootstrap/templates/ansible/inventory/group_vars/kubernetes/main.yaml.j2, bootstrap/templates/ansible/inventory/group_vars/kubernetes/supplemental.yaml.j2, bootstrap/templates/ansible/playbooks/templates/kube-vip-static-pod.yaml.j2.j2, bootstrap/templates/k0s-config.yaml.j2, bootstrap/vars/config.sample.yaml
Also update the var `bootstrap_kubeapi_hostname` to `bootstrap_kube_api_hostname`
=> fix: kube-vip was not rendering when enabled

.github/workflows/e2e.yaml, .taskfiles/Ansible/Taskfile.yaml, .taskfiles/Flux/Taskfile.yaml, .taskfiles/K0s/Taskfile.yaml, .taskfiles/Kubernetes/Taskfile.yaml, .taskfiles/Repo/Taskfile.yaml, .taskfiles/Repository/Taskfile.yaml, .taskfiles/Sops/Taskfile.yaml, .taskfiles/Workstation/Taskfile.yaml, Taskfile.yaml, bootstrap/scripts/py_version_check.py
Add python version check to taskfile and update taskfiles
=> feat: add python version check

bootstrap/vars/addons.sample.yaml
Looks like this comment was missed when the `monitoring` namespace was changed to `observability` in 
https://github.com/onedr0p/flux-cluster-template/pull/1110.
=> Update addons.sample.yaml with correct namespace for kubernetes-dashboard

.github/workflows/lychee.yaml
Currently lychee workflow is failing on missing .git directory. This PR adds checkout action to the workflow to fix the issue.
=> fixes: lychee pipeline workflow

.github/tests/config-k0s.yaml, .github/tests/config-k3s-ipv4.yaml, .github/tests/config-k3s-ipv6.yaml, .github/tests/config-talos.yaml, .taskfiles/Flux/Taskfile.yaml, README.md, bootstrap/templates/kubernetes/bootstrap/github-deploy-key.sops.yaml.j2, bootstrap/templates/kubernetes/flux/config/cluster.yaml.j2, config.sample.yaml
Fixes: https://github.com/onedr0p/cluster-template/issues/1137
=> feat: add first class support for private github repos

bootstrap/templates/kubernetes/talos/talconfig.yaml.j2, config.sample.yaml
This is the PR for https://github.com/onedr0p/cluster-template/discussions/1251#discussioncomment-8274805. This is to allow node-specific customizations for Talos to be retained when running `task configure` and `task talos:genconfig`. This also adds support to these tasks for installing Talos system extensions (See: https://github.com/onedr0p/cluster-template/issues/1248). 
For NodeConfig additions see: https://budimanjojo.github.io/talhelper/latest/reference/configuration/#nodeconfigs
For available system extensions: https://github.com/siderolabs/extensions
Example Usage (Adds Proxmox VM Guest Agent & CPU Microcode / GPU Pass-through support)
```
cluster:
nodes:
inventory:
- name: "talos-a"
address: "192.168.1.100"
controller: true
talos_disk_device: "/dev/sda"
talos_node_config: …
```
=> feat: Support talhelper NodeConfig additions

bootstrap/templates/kubernetes/talos/talconfig.yaml.j2, config.sample.yaml
The `talconfig.yaml` can easily support vlan tagging by shifting it's network block indentation and adding a "vlanId" key. I added this under `cluster.nodes.talos.vlan` but suspect it could exist under `cluster.nodes.vlan` or similar if you need to add support for the other distributions.
Documentation: https://www.talos.dev/v1.6/advanced/advanced-networking/#vlans
=> feat: Talos network vlan tagging

bootstrap/templates/kubernetes/apps/network/cloudflared/app/configs/config.yaml.j2
Cloudflared is reporting `ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp: lookup nginx-external-controller.network.svc.cluster.local on 10.96.0.10:53: no such host"`. The hostname in its config.yaml was missing the "ingress-" prefix.
=> fix(cloudflare): Update ingress-nginx-external-controller service name

bootstrap/templates/ansible/inventory/group_vars/kubernetes/main.yaml.j2, bootstrap/templates/ansible/inventory/group_vars/master/main.yaml.j2, bootstrap/templates/kubernetes/apps/system-upgrade/k3s/ks.yaml.j2
- Updates k3s to 1.29.1
- Enables [Spegel embedded registry](https://docs.k3s.io/installation/registry-mirror)
Fixes https://github.com/onedr0p/cluster-template/issues/1049
=> feat: upgrade k3s to 1.29.1 and enable the spegel embedded registry

bootstrap/templates/kubernetes/talos/talconfig.yaml.j2
On talos the openebs-hostpath PVCs fail to mount due to "not found" errors. Talos [documentation](https://www.talos.dev/v1.6/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/#preparing-the-nodes) notes the "/var/openebs/local" path mounts point needs to be mounted in the kubelet to be accessible to kubernetes. The docs comment about OpenEBS Jiva for replicated storage, but the same still applies for our local hostpath implementation too. Once my talos nodes had this added, PVCs with storageClass `openebs-hostpath` succeeded to mount and be usable.
=> fix(talos): Mount openebs-hostpath in kubelet

bootstrap/templates/kubernetes/apps/kube-system/cilium/app/cilium-bgp.yaml.j2, bootstrap/templates/kubernetes/apps/kube-system/cilium/app/kustomization.yaml.j2, bootstrap/templates/kubernetes/flux/vars/cluster-settings.yaml.j2, bootstrap/templates/partials/cilium-values-full.partial.yaml.j2, bootstrap/templates/partials/cilium-values-init.partial.yaml.j2, config.sample.yaml
When using VLAN network separation, Cilium's L2 announcements may not traverse the L2 network segments. When this is the case, it can help to have Cilium switch to BGP control plane mode and handle advertising the LoadBalancer IPs via a router instead. This requires a router with BGP support such as pfSense with the FRR package installed (or similar).
In this PR I am re-using the existing `CiliumLoadBalancerIPPool` from cilium-l2.yaml named "pool". Since this switches from L2 announcements to BGP, their is no conflict and `multi-pool` IPAM is not required to support both simultaneously. The "LOADBALANCER_CIDR" cluster-wide var is used for tracking this. 
The bgp settings maybe movable in the future to outside the talos dict to be used by kube-vip if cilium CNI is not in use.
The …
=> feat(talos): Add cilium bgpControlPlane support and CNI security settings

bootstrap/templates/kubernetes/apps/system-upgrade/system-upgrade-controller/app/rbac.yaml.j2, bootstrap/templates/kubernetes/talos/talconfig.yaml.j2
Great work on adding SUC to this template. I've tested your code, but the health check errors out having to less permissions with `os:operator` right. Granting `os:admin` works for performing the health check and upgrade Talos to new versions automagicly. Tested from 1.6.2 to 1.6.4.
=> Fix Talos SUC ServiceAccount

bootstrap/templates/kubernetes/bootstrap/kustomization.yaml.j2
Resource names differ in the installation manifests installed by the install file found on the flux/fluxcd2 github repo and the oci artifact oci://ghcr.io/fluxcd/flux-manifests. This commit introduces patches to the bootstrap kustomization to rename the resources to match the oci manifests.
=> fix(bootstrap): patch flux resource names to match oci manifests

.github/tests/config-talos.yaml, README.md, bootstrap/templates/kubernetes/apps/system-upgrade/kustomization.yaml.j2, bootstrap/templates/kubernetes/apps/system-upgrade/talos/.mjfilter.py, bootstrap/templates/kubernetes/apps/system-upgrade/talos/app/plan.yaml.j2, bootstrap/templates/kubernetes/talos/talconfig.yaml.j2, config.sample.yaml
As discussed briefly on Discord.
Modified both talhelper and SUC config to use only SchematicID
=> Talos: remove deprecated System Extentions and move to schematicID

bootstrap/templates/kubernetes/talos/talconfig.yaml.j2
Tested my yesterdays PR on virtualised cluster and noticed the VIP didn't come up due to Predictable NIC naming being enabled. Fixed by patching install which persists upgrades/install. See [here](https://www.talos.dev/v1.6/talos-guides/network/predictable-interface-names/#single-network-interface)
=> Adding kernel argument to disable predictable NIC naming. Fixes VIP

bootstrap/templates/kubernetes/apps/kube-system/cilium/app/kustomization.yaml.j2
In PR 1296 I accidentally [inversed ](https://github.com/Wasurerarenai/cluster-template/blob/a5761d67c35b9ccc90f1a2844d8fa25e53dcef1d/bootstrap/templates/kubernetes/apps/kube-system/cilium/app/kustomization.yaml.j2#L8-L10) the correct feature_gates.dual_stack_ipv4_first detection logic. This caused Talos distributions without BGPCP enabled to not include the cilium-l2.yaml file needed. This patch allows the cilium-l2.yaml inclusion to be generated when talos bgp or feature_gates.dual_stack_ipv4_first are disabled, and removed when either are present.
=> fix(cilium): Correct L2 kustomization exclusion logic

bootstrap/templates/kubernetes/talos/talconfig.yaml.j2, config.sample.yaml
I've added secureboot and system disk encryption support to the talos config block and talconfig template. Talhelper added support in [v2.2.0](https://github.com/budimanjojo/talhelper/commit/606f72f4f98eb7904c1905a67532211cad49a0c2). The [machineSpec](https://budimanjojo.github.io/talhelper/latest/reference/configuration/#machinespec) secureboot field usually modifies the talosImageURL by replacing "installer" with "installer-secureboot". I added this to the jinja template to keep with the support added for schematicID and SUC.
The  system disk can also be encrypted, sealed, and unsealed automatically via secure keys stored in the TPM 2.0 module. Talos gives us an example [here](https://www.talos.dev/v1.6/talos-guides/install/bare-metal-platforms/secureboot/#disk-encryption-with-tpm) …
=> feat(talos): Add secureboot & tpm-based disk encryption support

bootstrap/templates/kubernetes/apps/kube-system/cilium/app/cilium-bgp.yaml.j2, bootstrap/templates/kubernetes/talos/talconfig.yaml.j2, config.sample.yaml
=> feat(talos): Add option to specify other gateway

bootstrap/overrides/readme.partial.yaml.j2, makejinja.toml
In some cases its useful to override the templates from this repository with user defined customizations. We can include a simple "bootstrap/overrides" directory to provide a location (and readme example with links) that makejinja will process after running through the repository's baseline configuration. This helps the user keep following this repository for community updates while being able to patch in their own modifications that won't be overwritten and cause merge conflicts (from template repository updates).
This also doubles to provide a location where we can test additions to the repo without needing to modify the source files.
=> Allow users to optionally override templates

bootstrap/templates/kubernetes/talos/talconfig.yaml.j2, config.sample.yaml
Talhelper allows us to include [external patch files](https://github.com/budimanjojo/talhelper/blob/179ba9ed42f70069c7842109bea24f769f7af6eb/example/talconfig.yaml#L134) outside of the main `talconfig.yaml`. We can use this feature to allow the user to create [patches](https://github.com/budimanjojo/talhelper/blob/179ba9ed42f70069c7842109bea24f769f7af6eb/example/extraKernelArgs-patch.yaml) that can be maintained separately from the template generated talconfig. This can be used similarly to [this PR](https://github.com/onedr0p/cluster-template/pull/1319) for talos specific overrides.
When enabling `distribution.talos.user_patches` the includes for the following files are added to the generated talconfig.yaml. These patches are applied to the talconfig file's sections of the same name. 
- …
=> feat(talos): Allow users to include talhelper patches

bootstrap/templates/partials/cilium-values-full.partial.yaml.j2, bootstrap/templates/partials/cilium-values-init.partial.yaml.j2
It could cause issues/complications with more advanced networking configuration on the host (e.g. using FRR OpenFabric for host-level routing between nodes, or using other eBPF apps with Cilium). 
There's also no real advantage to using in homelab, so it should be safer to disable this.
=> fix(cilium): disable BPF masquerade

bootstrap/templates/ansible/playbooks/cluster-kube-vip.yaml.j2
The playbook uses the generated cluster-kube-vip.yaml, not the template file.
=> Fix cluster-kube-vip playbook

makejinja.toml
Looks like the logic was reversed in #1319. That change allowed non-existant files in bootstrap/templates to be created, but couldn't override existing files. The inputs need to be swapped to allow the overrides to be applied with preference (if they exist).
This affect can be seen in makejinja's examples:
- https://github.com/mirkolenz/makejinja/blob/main/tests/data/makejinja.toml
- inputs = ["./input1", "./input2"]
- https://github.com/mirkolenz/makejinja/blob/main/tests/data/input1/not-empty.yaml.jinja
- https://github.com/mirkolenz/makejinja/blob/main/tests/data/input2/not-empty.yaml.jinja
- https://github.com/mirkolenz/makejinja/blob/main/tests/data/output/not-empty.yaml
This allowed me to apply a patch to the ingress-nginx instances without changing the source template files.
```
$ …
```
=> fix: Allow users to optionally override templates

Taskfile.yaml
Go-task supports [including optional](https://taskfile.dev/usage/#optional-includes) user taskfiles and directories . This allows us to use our own custom tasks without needing to edit the repo root Taskfile.yaml. Useful for reducing merge conflicts in the future for those following along with the cluster-template's regular updates.
Example:
```
$ find .taskfiles/User
.taskfiles/User
.taskfiles/User/app1
.taskfiles/User/app1/Taskfile.yaml
.taskfiles/User/app2
.taskfiles/User/app2/Taskfile.yaml
.taskfiles/User/Taskfile.yaml
$ cat .taskfiles/User/Taskfile.yaml
version: '3'
includes:
app1: app1
app2:
taskfile: app2
$ cat .taskfiles/User/app1/Taskfile.yaml
version: '3'
tasks:
greet1:
cmds:
- echo app1
desc: test2
$ cat .taskfiles/User/app2/Taskfile.yaml
version: '3'
tasks:
greet2:
cmds:
- …
```
=> Add optional user tasks to Taskfile.yaml

bootstrap/templates/ansible/inventory/hosts.yaml.j2, config.sample.yaml
I personally prefer to store key as a named value in my `~/.ssh/` directory, but the configs have no way of allowing for that (or at least I wasn't able to find any) - this should account for it, and only set it when that variable has been specified.
It was my first time editing jinja templates, so I hope it's fine - it works a-okay on my end.
=> Add the option for assigning a specific SSH key to a node.

bootstrap/templates/kubernetes/apps/network/echo-server/app/helmrelease.yaml.j2
Ran into flux-local errors for echo-server's ingress service until its service name/identifier was updated to match the new app-template v3 service name.
=> Update echo-server app-template ingress' v3 service identifier

bootstrap/templates/ansible/playbooks/cluster-prepare.yaml.j2
According to the errors in the logs, cillium also requires the following modules
- iptable_mangle
- iptable_raw
- xt_socket
=> Add kernel modules required by cilium

bootstrap/templates/ansible/playbooks/cluster-nuke.yaml.j2, bootstrap/templates/partials/cilium-values-full.partial.yaml.j2, bootstrap/templates/partials/cilium-values-init.partial.yaml.j2
Cilium incorrectly uses the `/etc/cni/net.d` and `/opt/cni/bin` directories in the node filesystem instead of the corresponding directories in `/var/lib/rancher/k3s`.
=> Fix cilium to use k3s paths for binPath and confPath

bootstrap/templates/ansible/playbooks/cluster-nuke.yaml.j2, bootstrap/templates/partials/cilium-values-full.partial.yaml.j2, bootstrap/templates/partials/cilium-values-init.partial.yaml.j2
@prehor I need to revert this change. People are reporting issues in Discord https://discord.com/channels/673534664354430999/1221220838812946523
As I know this works with the previous paths I feel it's safe to revert and maybe debug what is the root cause
Reverts onedr0p/cluster-template#1381
=> Revert "Fix cilium to use k3s paths for binPath and confPath"

bootstrap/templates/kubernetes/apps/kube-system/metrics-server/app/helmrelease.yaml.j2
According to https://www.talos.dev/v1.6/kubernetes-guides/configuration/deploy-metrics-server, this flag is not necessary when enabling certificate rotation and an auto CSR approver.
=> fix(metrics-server): Remove --kubelet-insecure-tls

bootstrap/scripts/validation.py
Validation.py script unnecessarily checking for node.ssh_user when distribution is set to "talos".
=> Disable node.ssh_user check

bootstrap/templates/kubernetes/bootstrap/talos/talconfig.yaml.j2, config.sample.yaml
When setting up my new Talos-based cluster, I stumbled upon an issue with case sensitivity.
The Terraform provider for Proxmox wanted the MAC address to be uppercase, so I made it as such in the config, from which I sourced the address (for idempotence and DRY sake). In turn, Talos could not assign the VIP to any node. After making the MAC address lowercase (and just using upper() in Terraform), the VIP worked successfully.
I am adding this in the documentation, so that no other homelabber has issue with this. This could probably also be fixed with a PR to Talos, but for now, I'm adding this to the documentation.
Relevant issue in Talos's repo: https://github.com/siderolabs/talos/issues/8176
=> Make deviceSelector.hardwareAddr in config.yaml case-insensitive

.taskfiles/Talos/Taskfile.yaml
when local k8s context is set to different k8s cluster helmfile pick the local context instead of talos context for Task talos:bootstrap
before the change:
after the change:
=> add kubeconfig flag to helmfile

bootstrap/templates/ansible/playbooks/cluster-installation.yaml.j2, bootstrap/templates/ansible/playbooks/cluster-nuke.yaml.j2, bootstrap/templates/partials/cilium-values-full.partial.yaml.j2, bootstrap/templates/partials/cilium-values-init.partial.yaml.j2
Cilium incorrectly uses the `/etc/cni/net.d` and `/opt/cni/bin` directories in the node filesystem instead of the corresponding directories in `/var/lib/rancher/k3s`.
Fixes PR #1381 where links `/etc/cni/net.d` and `/opt/cni/bin` to the corresponding directories in `/var/lib/rancher/k3s` were missing.
=> Fix cilium to use k3s paths for binPath and confPath v2

README.md
I ran into two issues while running to bootstrap my Talos cluster:
1. The cluster was left in a partially-initialized, non-functional state after running the command without the required environment variables were not set (see also: #1437).
2. After fixing that issue, I assumed that all of the permission errors spam indicated that something was still wrong - so I <kbd>Ctrl</kbd> + <kbd>C</kbd>ed the process after a few minutes. 
This PR adds a note to the README that the `talos:bootstrap` command (1) may take a while, (2) outputs a bunch of error messages, and (3) may require nuking the cluster if interrupted.
=> Clarify talos:bootstrap setup instructions

README.md
I missed the `task workstation:direnv` command in the README because of the way it is formatted. Instead of being called out in a code block, like the other steps, it is inlined as part of another step. It is also not obvious how to tell whether the setup was successful.
This sent me down a bit of a rabbit hole because several of the following steps fail in surprising ways (e.g. TLS errors) when the env variables are missing. I thought I had setup `direnv` correctly, but actually had missed a step.
This PR modifies the README to callout `task workstation:direnv` as a separate step and explains how to check whether it was successful. Hopefully this will will prevent someone else from going down the same rabbit hole. 😄 
P.S. `direnv` is really neat! I am going to start using it everywhere!
=> Clarify direnv setup instructions

bootstrap/templates/partials/kube-vip-ds.partial.yaml.j2
Should we add: `# renovate: datasource=github-releases depName=kube-vip/kube-vip`?
=> chore: update kube-vip

.taskfiles/Talos/Taskfile.yaml, bootstrap/templates/kubernetes/bootstrap/talos/helmfile.yaml.j2
helmfile error
`in /Users/hz323328/Personal/cluster-template/kubernetes/bootstrap/talos/helmfile.yaml: release(s) "kube-system/cilium", "kube-system/coredns", "kube-system/kubelet-csr-approver", "kube-system/spegel" depend(s) on an undefined release "kube-system/prometheus-operator-crds". Perhaps you made a typo in "needs" or forgot defining a release named "prometheus-operator-crds" with appropriate "namespace" and "kubeContext"?
`
Taskfile error
```
task talos:nuke 
error:
unknown flag: --reboot--system-labels-to-wipe
Usage:
talosctl reset [flags]
Flags:
--debug                                    debug operation from kernel logs. --wait is set to true when this flag is set
--graceful                                 if true, attempt to cordon/drain node and leave etcd (if applicable) …
```
=> fix helmfile for prometheus-operator-crds dependsOn and Taskfile talos:nuke error

.taskfiles/Talos/Taskfile.yaml, bootstrap/templates/kubernetes/bootstrap/talos/helmfile.yaml.j2
`Comparing release=prometheus-operator-crds, chart=/var/folders/w2/dpq8tgkd3rdbmdw3w52vwdw40000gp/T/helmfile773241121/observability/prometheus-operator-crds/prometheus-operator-crds/11.0.0/prometheus-operator-crds
in /Users/hz323328/Personal/cluster-template/kubernetes/bootstrap/talos/helmfile.yaml: failed processing release cilium: values file matching "../../../../apps/kube-system/cilium/app/helm-values.yaml" does not exist in "."`
=> Fix helmvalue path

bootstrap/templates/kubernetes/bootstrap/talos/talconfig.yaml.j2, config.sample.yaml
Talos v1.7 now requires [ExtensionServiceConfig's](https://www.talos.dev/v1.7/reference/configuration/extensions/extensionserviceconfig/) defined for configuring [System Extensions](https://www.talos.dev/v1.7/talos-guides/configuration/system-extensions/) (ex. nut-config). Talhelper added support for these in https://github.com/budimanjojo/talhelper/pull/431, but including these in `config.yaml` looks like it could get pretty messy.
The node.extraManifests object supports including external files and works for including these needed configs. This patch adds parsing of the bootstrap_node_inventory[].manifests key to allow these to be included.
Example `config.yaml`
```
bootstrap_node_inventory:
- name: node1
...
manifests:
- manifests/nut-config.yaml
```
Results in:
```
$ talhelper …
```
=> Allow extraManifests to be specified

bootstrap/templates/kubernetes/bootstrap/talos/talconfig.yaml.j2, config.sample.yaml
Similar to #1495 (which didn't support talenv.sops.yaml envsubst), this adds further support for https://github.com/budimanjojo/talhelper/pull/431. With talenv envsubst, secrets can be encrypted, and automatically referenced when `talhelper genconfig` is ran. This patch adds support for talhelper's extensionServices inclusions.
extraManifests is still useful for adding manifests like v1.7's [WatchdogTimerConfig](https://www.talos.dev/v1.7/reference/configuration/runtime/watchdogtimerconfig/). 
Example `config.yaml`
```
bootstrap_node_inventory:
- name: node1
...
extension_services:
- name: nut-client
configFiles:
- content: MONITOR ${upsmonUpsName}@${upsmonHost}:${upsmonPort} 1 ${upsmonUser} ${upsmonPasswd} slave
mountPath: /usr/local/etc/nut/upsmon.conf
environment:
- UPS_NAME=ups
``` …
=> Allow extensionServices to be specified

bootstrap/templates/kubernetes/bootstrap/talos/talconfig.yaml.j2
Related to #1496. The first line of rendered extensionServices configFile content strings was not being indented correctly. Simple patch to correct formatting.
=> Fix extensionServices configFile content multi-line indentation.

bootstrap/scripts/plugin.py
#1509 generates patch file inclusions into the talconfig.yaml, but doesn't sort them. For better IaC adherence, its ideal to keep the lists generated consistent over multiple `task configure` runs by sorting it.
Example patches before, note the `##-` prefixed patches (order dependent patches here) not getting applied in the correct order. All order dependent patches for a section could be forced into a single file, but this allows them to be safely separated and ordered by name.
```
+    - "@./patches/controller/01-network-deviceSelector.yaml"
+    - "@./patches/controller/02-network-mtu.yaml"
+    - "@./patches/controller/cluster.yaml"
+    - "@./patches/controller/04-tpm-disk-encryption.yaml"
+    - "@./patches/controller/api-access.yaml"
+    - "@./patches/controller/etcd.yaml"
+    - …
```
=> Sort talos patches for consistency

.taskfiles/Flux/Taskfile.yaml, README.md
Add conditional check for existing sops-age secret in bootstrap task
=> fix: Add conditional check for existing sops-age secret in bootstrap task

bootstrap/templates/kubernetes/apps/cert-manager/cert-manager/app/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/network/ingress-nginx/external/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/network/ingress-nginx/internal/helmrelease.yaml.j2, bootstrap/templates/kubernetes/apps/network/k8s-gateway/app/helmrelease.yaml.j2, bootstrap/templates/kubernetes/bootstrap/talos/patches/global/sysctl.yaml.j2
Replaced deprecated 
```yaml
installCRDs: true
``` 
with the equivalent:
```yaml
crds:
enabled: true
keep: true
```
[Default Helm Chart Values](https://artifacthub.io/packages/helm/cert-manager/cert-manager?modal=values&path=installCRDs)
Updated the deprecated load balancer annotation key:
```yaml
io.cilium/lb-ipam-ips
```
to:
```yaml
lbipam.cilium.io/ips
```
[IP Requesting Documentation](https://docs.cilium.io/en/stable/network/lb-ipam/#requesting-ips)
Cloudflared uses QUIC UDP, triggering a log warning about insufficient buffer size. Increasing the buffer to `7500000` resolves this issue, as per the recommendation:
[UDP QUIC Buffer Documentation](https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes)
=> Various Improvements

.taskfiles/Sops/Taskfile.yaml
**Problem:**
The SOPS encryption task was failing with the error "command line too long" when processing many files using `xargs`. This happened because the number of files found by `find `exceeded the system's command-line length limit.
**Solution:**
- Replaced `xargs` with a `while read -r` loop to process each file individually, avoiding command length limits.
- Relocated existing precondition checks in the encryption task.
**Changes:**
- Added shell checks for the SOPS configuration and Age key file at the beginning of the encryption task.
- Replaced the `xargs` command with a while loop to handle file encryption without exceeding command-line length limitations.
This PR fixes the command line limit issue while retaining the original precondition checks to ensure all necessary files …
=> Fix 'xargs: command line too long' in SOPS encryption task

.envrc, .taskfiles/Flux/Taskfile.yaml, .taskfiles/Kubernetes/Taskfile.yaml, .taskfiles/Repository/Taskfile.yaml, .taskfiles/Sops/Taskfile.yaml, .taskfiles/Talos/Taskfile.yaml, .taskfiles/Workstation/Taskfile.yaml, Taskfile.yaml
All below changes will required at least go-task version 3.39.2
- Update taskfiles to use styling guide (UPPER vars)
- Enable taskfile to override system environment vars via direnv (simplifies `KUBECONFIG` and `SOPS_AGE_KEY_FILE` vars)
- Nits with quotes and lists in taskfiles
- Move certain vars in taskfiles to their respective taskfile
=> chore: update taskfiles and direnv

.taskfiles/talos/Taskfile.yaml
During updating the config of my cluster I discovered the task had some redundant braces.
Example: 
```sh
task talos:apply-node HOSTNAME=control-1 MODE=auto
task: [talos:apply-node] talosctl --nodes control-1 apply-config --mode=auto}} --file /home/runner/cluster/kubernetes/bootstrap/talos/clusterconfig/cluster-control-1.yaml
invalid argument "auto}}" for "-m, --mode" flag: possible options are: auto, interactive, no-reboot, reboot, staged, try
```
This PR fixes that.
=> fix(taskfile): remove redundant braces

bootstrap/templates/kubernetes/bootstrap/talos/patches/controller/cluster.yaml.j2, bootstrap/templates/kubernetes/bootstrap/talos/patches/global/cluster-discovery.yaml.j2
Prevents log spam and maybe other issues
```
master-0.ishioni.casa: user: warning: [2024-12-18T22:55:14.499355998Z]: [talos] kubernetes registry node watch error {"component": "controller-runtime", "controller": "cluster.KubernetesPullController", "error": "failed to list *v1.Node: nodes is forbidden: User \"system:node:master-0\" cannot list resource \"nodes\" in API group \"\" at the cluster scope: node 'master-0' cannot read all nodes, only its own Node object"}
```
=> fix: update talos service discovery

config.sample.yaml, templates/config/kubernetes/bootstrap/talos/talconfig.yaml.j2
These aren't needed to get a working cluster ready and can be done with a talos upgrade later on. These options will just confuse people getting started.
=> fix(template): remove options for extra manifests and extension config

templates/config/kubernetes/flux/config/cluster.yaml.j2
flux failing due to not finding github.private_key when using config sample.
=> correct github private key reference in cluster.yaml.j2

templates/config/kubernetes/apps/network/ingress-nginx/external/helmrelease.yaml.j2, templates/config/kubernetes/apps/network/ingress-nginx/internal/helmrelease.yaml.j2
adding back the network namespace that was (unintentionally?) removed in https://github.com/onedr0p/cluster-template/commit/3659673e2d3cb1bfd0f9e30b9cabedbde014a0ba
=> fix ssl cert for ingresses

config.sample.yaml, templates/config/kubernetes/bootstrap/talos/talconfig.yaml.j2
Moving the global secureboot/encrypt_disk option to be node specific. Useful for multi-arch clusters where some nodes don't support one of those options, like older NUCs or Raspberry Pi's SBCs.
=> Node secureboot and disk encrypt

.taskfiles/bootstrap/Taskfile.yaml, .taskfiles/talos/Taskfile.yaml, .taskfiles/template/Taskfile.yaml, Taskfile.yaml
`talhelper validate talconfig` doesn't automatically pickup encrypted variables in the `talenv.sops.yaml` when executed outside of the talos directory. This can be overridden by specifying `--env-file path/to/talenv.sops.yaml` but not everyone will be using this file so we should not add it to the template:validate-talos-config cmd value. Instead we can utilize the `dir` key from https://taskfile.dev/usage/#task-directory to automatically have the working directory of the command use the directory containing the talenv.sops.yaml file. This allows the task to succeed in both situations, when using encrypted variables and without.
The `bootstrap:talos` and `talos:reset` tasks already had this set. This PR is to add this to the other tasks using talhelper which similarly have issues when …
=> Execute talhelper commands within the talos directory

.github/tests/config-talos.yaml, config.sample.yaml, templates/config/kubernetes/apps/cert-manager/cert-manager/issuers/clusterissuers.yaml.j2, templates/config/kubernetes/flux/meta/settings/cluster-secrets.sops.yaml.j2
This field isn't needed anymore since LE will stop sending emails reminding of cert expiry
=> fix: remove email from config and cert manager

.github/workflows/flux-local.yaml
- This is needed for private repos as setting the permission overwites ALL permissions.
- See https://github.com/actions/checkout/issues/254#issuecomment-981945812 for the explanation for a similar issue.
=> Add read permission for flux local diff workflow

README.md
cloudflare_gateway_vip was renamed to cloudflare_dns_gateway_addr, let's change the README.md to reflect that.
=> Use new variable name in README.md

templates/config/bootstrap/github-deploy-key.sops.yaml.j2
In #1791 a `strip()` was added to a bunch of strings read from files. However, this also removes newlines, so for the github-deploy-key the `known_hosts` would end up on the same line as the end of the private key and therefore not work in the `source-controller`.
Instead of removing the `strip()` let's remove the `-` sign in the jinja end block so we keep newline after it.
=> Add back missing newline in github-deploy-key

.taskfiles/template/resources/nodes.schema.cue
Updated the node schema to add optioanal secureboot and encrypt_disk fields in schema.
=> Fix: Allow secureboot and encrypt_disk fields to be optional

templates/config/kubernetes/apps/network/external/ingress-nginx/helmrelease.yaml.j2, templates/config/kubernetes/apps/network/internal/ingress-nginx/helmrelease.yaml.j2
When value is high header has scientific notation value
ex: `max-age=1.5552e+07; includeSubDomains`.
Which is not valid according to following  
https://datatracker.ietf.org/doc/html/rfc6797#section-6.1.1
=> fix: make hsts-max-age well formed

.taskfiles/bootstrap/Taskfile.yaml, .taskfiles/template/Taskfile.yaml
- On Intel Mac the homebrew binaries are located at /usr/local/bin/ instead of /opt/homebrew/bin, let's include the Intel Mac path in the check as well.
- See https://docs.brew.sh/Installation for more details on possible install configurations.
- Checking the actual versions of these binaries would be better but this works fine for now.
=> Make bash and gsed brew availability check Intel Mac compatible

templates/config/.sops.yaml.j2, templates/config/kubernetes/apps/network/external/cloudflared/dnsendpoint.yaml.j2, templates/config/kubernetes/apps/network/external/cloudflared/helmrelease.yaml.j2, templates/config/kubernetes/apps/network/external/cloudflared/secret.sops.yaml.j2, templates/config/kubernetes/components/common/sops-age.sops.yaml.j2, templates/scripts/plugin.py
With `cloudflared` use `TUNNEL_TOKEN` instead of mounting in the creds.json and passing the tunnel id as an arg.
`TUNNEL_TOKEN` must be base64encoded, e.g.
```yaml
apiVersion: v1
kind: Secret
metadata:
name: cloudflared-secret
stringData:
TUNNEL_TOKEN: |
eyJhIjoiZmFrZSIsInQiOiJmYWtlIiwicyI6ImZha2UifQ==
```
```bash
echo "eyJhIjoiZmFrZSIsInQiOiJmYWtlIiwicyI6ImZha2UifQ==" | base64 -d
{"a":"fake","t":"fake","s":"fake"}
```
=> feat: improve makejinja functions and cloudflared deployment

scripts/bootstrap-apps.sh, templates/config/talos/patches/controller/cluster.yaml.j2
The way Talos handles `extraManifests` is quite odd. Talos may potentially downgrade the items in `extraManifests` if the cluster admin **did not apply the talos config** after merging the PR that upgrades the CRDs in the `extraManifests`. This isn't ideal so I've moved them back into the bootstrap script.
Moving forward I would rather support only having these crds be applied on bootstrap and then the cluster taking over the management lifecycle and not deal with the nuances of `extraManifests`
=> fix: move installation of crds to bootstrap script

scripts/bootstrap-apps.sh, templates/config/kubernetes/apps/cert-manager/cert-manager/ks.yaml.j2, templates/config/kubernetes/apps/default/echo/ks.yaml.j2, templates/config/kubernetes/apps/flux-system/flux-instance/ks.yaml.j2, templates/config/kubernetes/apps/flux-system/flux-operator/ks.yaml.j2, templates/config/kubernetes/apps/kube-system/cilium/ks.yaml.j2, templates/config/kubernetes/apps/kube-system/coredns/ks.yaml.j2, templates/config/kubernetes/apps/kube-system/metrics-server/ks.yaml.j2, templates/config/kubernetes/apps/kube-system/reloader/ks.yaml.j2, templates/config/kubernetes/apps/kube-system/spegel/ks.yaml.j2, templates/config/kubernetes/apps/network/external/external-dns/helmrelease.yaml.j2, templates/config/kubernetes/apps/network/external/ingress-nginx/helmrelease.yaml.j2, templates/config/kubernetes/apps/network/external/ks.yaml.j2, templates/config/kubernetes/apps/network/internal/ks.yaml.j2, templates/config/kubernetes/flux/cluster/ks.yaml.j2
- That patch ended up interfering with postBuilds set on individual app ks
- Install external-dns endpoint CRD on bootstrap (this never changes and removes some dependsOn)
=> feat: remove global postbuild patch

.github/workflows/flux-local.yaml
- Read permissions are needed for private repos, and was actually initially added in #1742.
- This was removed in a refactor in #1791, let's add it back so it works with private repos again.
=> Add back read permission in flux-local workflow

templates/config/kubernetes/apps/kube-system/cilium/app/networks.yaml.j2
Update `CiliumBGPPeeringPolicy` to BGP V2 `CiliumBGPClusterConfig`, `CiliumBGPPeerConfig`, `CiliumBGPAdvertisement`.
Ties to discussion:
#1855
=> feat(cilium): update BGP configuration to use cluster config and peer settings

templates/config/kubernetes/apps/kube-system/cilium/app/networks.yaml.j2
The Cilium BGP node and router ASNs we're swapped in https://github.com/onedr0p/cluster-template/discussions/1855 suggestion. I began seeing "as number mismatch" errors in the cilium-agent logs after adoption of that change. Swapping these assignments allowed BGP peering to correctly be established.
```
The Cilium BGP node and router ASNs we're swapped in https://github.com/onedr0p/cluster-template/discussions/1855 suggestion. I began seeing "as number mismatch" errors in the cilium-agent logs after adoption of that change. Swapping these assignments allowed BGP peering to correctly be established.
cilium-thkmp cilium-agent time="2025-04-22T15:22:44.84449563Z" level=warning msg="sent notification" Data="as number mismatch expected 64514, received 64513" Key=10.0.0.1 Topic=Peer asn=64513 …
```
=> Swap Cilium BGP Node/Router ASNs

scripts/bootstrap-apps.sh
CRD path was changed in https://github.com/kubernetes-sigs/external-dns/pull/5287 it seems
=> chore(external-dns): update CRD path

.github/workflows/label-sync.yaml
Fix for `Error: ✗ {"message":"Resource not accessible by integration","statusCode":403, ...}` on new repositories.
=> fix: set token permissions for label-sync

.github/workflows/labeler.yaml
this should fix an error I hit here: https://github.com/hef/house-cluster/actions/runs/16392247611/job/46319757253#step:2:9
```
{"resource":"Repository","field":"label","code":"unauthorized"}
Error: You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"}
```
=> fix labeler permissions

templates/config/talos/patches/global/machine-registries.yaml.j2
Reverts onedr0p/cluster-template#1946
This does not work with spegel
=> Revert "feat: use gcr mirror for docker.io pulls"
