onedr0p/cluster-template

README.md

Ugly but actually substitutes the ENV vars

[FIX] Actually substitute ENV

---

cluster/base/flux-system/charts/helm/metallb-charts.yaml
cluster/core/metallb-system/helm-release.yaml

feat: use the official metallb chart

---

cluster/apps/system-upgrade/system-upgrade-controller/agent-plan.yaml
cluster/apps/system-upgrade/system-upgrade-controller/server-plan.yaml

Align system upgrader version with template instructions
**Benefits**
No more imediate downgrade after install
- fixes #

Align system upgrader version with template instructions 

---

cluster/apps/kube-system/metrics-server/helm-release.yaml
cluster/apps/kube-system/metrics-server/kustomization.yaml
cluster/base/flux-system/charts/helm/kustomization.yaml
cluster/base/flux-system/charts/helm/metrics-server-charts.yaml

Use the official metrics server helm chart
**Benefits**
Helm chart > Kusomtization
- fixes #72

Migrate to metrics-server helm chart

---

README.md

Doc update
**Benefits**
People will delete this unneeded dir!
🤷‍♂️ 
- fixes #

chore: add note about cleaning up the tmpl dir

---

README.md
provision/ansible/inventory/group_vars/kubernetes/k3s.yml
provision/ansible/roles/ubuntu/tasks/main.yml

1. remove kubernetes dir in playbooks task
2. remove unattended
3. remove kube-vip dir in templates
4. change adhoc:ping
5. add task ansible:deps

fix: modified the ansible docs

---

README.md
provision/ansible/inventory/group_vars/kubernetes/k3s.yml
provision/ansible/inventory/group_vars/master/k3s.yml
provision/ansible/playbooks/templates/calico-installation.yaml.j2

Signed-off-by: Devin Buhl <devin.kray@gmail.com>
Implement calico cni - too many problems with flannel

feat: implement calico cni - too many problems with flannel

---

README.md

Update README.md to make clear no security hardening is done on nodes and point to https://github.com/dev-sec/ansible-collection-hardening
**Benefits**
Make explicit what is and isn't done for the user.
Many users already know this.
- #137 
Tried to keep warning short but explicit.

Update README.md to make clear security hardening is not done for you.

---

provision/ansible/inventory/group_vars/kubernetes/k3s.yml
provision/ansible/inventory/group_vars/master/k3s.yml

Few minor changes that might be required once on k3s 1.22

feat: Bump k3s to v1.22.x

---

provision/ansible/playbooks/templates/kube-vip-daemonset.yaml.j2

* Bump to 0.4.0
* Sync with cluster template
**Benefits**
- fixes #

Bump kubevip 0.4.0 and sync with template

---

.taskfiles/ansible.yml

Fix incorrect description in the ansible task
**Benefits**
Correct description
None
Nuke k3s
`Install` -> `Uninstall`

fix(task): Ansible task fix typo

---

README.md

chore: discord url in readme

---

provision/ansible/inventory/group_vars/kubernetes/k3s.yml

https://github.com/k3s-io/k3s/releases/tag/v1.22.5%2Bk3s1
**Benefits**
Contains a couple of fixes that might be good to have from the start up.
- fixes #

Upgrade to k3s 1.22.5+k3s1

---

.pre-commit-config.yaml
.taskfiles/pre-commit.yml
README.md

1. Updated hook versions to latest
2. Added an arg that should exclude markdown from excessive white space cleaning
3. Edited the pre-commit:init task to fully install based on its help documentation
**Benefits**
Users unfamiliar with pre-commit will be fully setup while following the tutorial.
I have tested the new hook versions, and they appear to be fine, but you never know.

Update hooks; Exclude markdown; Better pre-commit install command

---

cluster/apps/kube-system/kustomization.yaml
cluster/apps/kube-system/reflector/helm-release.yaml
cluster/apps/kube-system/reflector/kustomization.yaml
cluster/base/flux-system/charts/helm/emberstack-charts.yaml
cluster/base/flux-system/charts/helm/kustomization.yaml

add emberstack/reflector - works on amd64/arm64/armv7
https://github.com/emberstack/kubernetes-reflector
**Benefits**
Useful tool to allow for syncing configmap or secrets to another namespace.

feat: add emberstack/reflector

---

README.md

Minor change for more usability!
To work, an internal link should not include emoji.

fix internal links

---

.github/renovate.json5

This should provide automated update for pre-commit modules
**Benefits**
More automated dependency update PRs to come.
It's still in beta.

renovate: Enable pre-commit module

---

README.md
cluster/apps/default/echo-server/helm-release.yaml
cluster/apps/networking/external-dns/helm-release.yaml
cluster/apps/networking/external-dns/kustomization.yaml
configure.sh
provision/terraform/cloudflare/main.tf
tmpl/cluster/external-dns-secret.sops.yaml

feat: add external-dns for managing public DNS records

---

cluster/apps/default/echo-server/helm-release.yaml

Adds traefik class to echo-server configuration and fixes access via ingress.

fix: Adds ingress class to echo-server service

---

.config.sample.env

Corrects a small typo
**Benefits**
Correct spelling
N/A
N/A
N/A

Typo in .config.sample.env

---

README.md

Fixes small typo / grammar issue in README
**Benefits**
N/A
N/A
N/A
N/A

Small typo / grammar fix in README

---

.taskfiles/ClusterTasks.yml
.taskfiles/PrecommitTasks.yml

Clean up some typos in the taskfile

.taskfiles: Fix some typos

---

.taskfiles/SopsTasks.yml
Taskfile.yml

adds two tasks to ecrypt and decrypt files for sops
**Benefits**
I couldn't figure out how this was done, and now its self documenting
could be a better way to run the command across all files in the repo.

adds sops tasks to encrypt and decrypt

---

.config.sample.env
cluster/apps/kube-system/kustomization.yaml
configure
provision/ansible/inventory/group_vars/kubernetes/k3s.yml

Allow disabling kube-vip, the previous PR missed to include the ansible changes.

Add option to disable kube-vip (part 2)

---

provision/ansible/playbooks/cluster-prepare.yml

Fixes Ansible cluster prepare script
**Benefits**
Ansible works again
none
None, no issue opened
- fixes #
n/a

Fix Ansible cluster prepare script

---

ansible.cfg
provision/ansible/inventory/group_vars/kubernetes/os.yml
provision/ansible/playbooks/cluster-prepare.yml

Fixes 3 issues I had on a fresh Fedora 36 minimal install:
- Had to change the Ansible remote_tmp dir because of permission issues to local user
- Added Python 3 SELinux module to dnf packages
- Included required SELinux policy
**Benefits**
Playbook finishes now without errors. I reverted all my VM's to the fresh installed state to confirm.
Not sure if changing the Ansible remote_tmp dir is the best solution. But I see no harm in changing the user.
none
n/a

Fix issues on Fedora Ansible scripts

---

cluster/apps/networking/kustomization.yaml

Wonder if this was accidentally left out

---

kubernetes/apps/kube-system/kube-vip/app/kustomization.yaml

Found this while helping in the Discord. Just a naming typo.

Fix Kustomization (kube-vip)

---

README.md

The original line returns a base64 encoded token
kubectl -n monitoring get secret kubernetes-dashboard -o jsonpath='{.data.token}' 
ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklucENlRUZ3WVhWRVUzUlNlbmhhVTJoSVVVaDBOMVUxVFVveFNYQlNRVEZaVFhsMWNtSjFXbDkxYXpnaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUp0YjI1cGRHOXlhVzVuSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaV055WlhRdWJtRnRaU0k2SW10MVltVnlibVYwWlhNdFpHRnphR0p2WVhKa0lpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkltdDFZbVZ5Ym1WMFpYTXRaR0Z6YUdKdllYSmtJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1ZFdsa0lqb2lPRE5pTkRVNU9EUXROelF5TWkwME1ERTVMVGc1TWpNdE5E …

Update Kubernetes Dashboard Secret Read Me

---

kubernetes/apps/kube-system/local-path-provisioner/app/helmrelease.yaml

Some more information in discord: https://discord.com/channels/673534664354430999/1063710847890903070

fix(local-path-provisioner): escape $ from helm

---

ansible/inventory/group_vars/kubernetes/k3s.yml
kubernetes/apps/system-upgrade/system-upgrade-controller/plans/agent.yaml
kubernetes/apps/system-upgrade/system-upgrade-controller/plans/server.yaml

Reverts onedr0p/flux-cluster-template#710

Revert "feat(github-release): update k3s-io/k3s to v1.27.1+k3s1"

---

.config.sample.env
configure
kubernetes/apps/monitoring/grafana/app/helmrelease.yaml
kubernetes/apps/monitoring/grafana/app/kustomization.yaml
kubernetes/apps/monitoring/grafana/ks.yaml
kubernetes/apps/monitoring/kube-prometheus-stack/app/helmrelease.yaml
kubernetes/apps/monitoring/kube-prometheus-stack/app/kustomization.yaml
kubernetes/apps/monitoring/kube-prometheus-stack/ks.yaml
kubernetes/apps/monitoring/kustomization.yaml
kubernetes/flux/repositories/helm/grafana.yaml
kubernetes/flux/repositories/helm/kustomization.yaml
kubernetes/flux/repositories/helm/prometheus-community.yaml
tmpl/kubernetes/grafana-admin-secret.sops.yaml

Adds grafana and the kube-prometheus-stack helmreleases

feat: Add grafana and kube-prometheus-stack HelmReleases

---

README.md
ansible/inventory/group_vars/kubernetes/os.yml
ansible/playbooks/cluster-prepare.yml

Closes: https://github.com/onedr0p/flux-cluster-template/issues/772

feat: Remove Fedora server as supported OS

---

kubernetes/apps/kube-system/cilium/app/helmrelease.yaml

Reverts onedr0p/flux-cluster-template#795

Revert "fix(helm): update chart cilium to 1.13.4"

---

.taskfiles/AnsibleTasks.yaml
.taskfiles/ClusterTasks.yaml
ansible/playbooks/cluster-kube-vip.yaml
ansible/playbooks/cluster-rollout-update.yaml

Playbook to rollout update the cluster

feat: cluster rollout update playbook & use new `cmd` for taskfiles

---

README.md
ansible/playbooks/cluster-prepare.yaml
template/templates/ansible/supplemental.yaml.j2

If starting from scratch Ubuntu _should_ still work with this playbook but I'll be moving forward with support for Debian 12.
Few comments on this change:
- Debian is more minimal (no snap, no tracking software)
- Debian doesn't have systemd-resolved - fixing search domain problems is easier (see [here](https://wiki.debian.org/resolv.conf))
- Debian is on kernel 6.1.0 (Ubuntu is on 5.15)
Some interesting migration notes:
- Debian doesn't have netplan, instead uses https://wiki.debian.org/NetworkConfiguration

feat!: debian 12 to the moon

---

README.md

Add hardware considerations and installation instructions.

Initial RPi considerations

---

template/tasks/addons/csi_driver_nfs.yaml
template/tasks/addons/main.yaml
template/templates/addons/csi-driver-nfs/app/helmrelease.yaml.j2
template/templates/addons/csi-driver-nfs/app/kustomization.yaml.j2
template/templates/addons/csi-driver-nfs/app/storageclass.yaml.j2
template/templates/addons/csi-driver-nfs/ks.yaml.j2
template/templates/kubernetes/apps/kube-system/kustomization.yaml.j2
template/templates/kubernetes/flux/repositories/helm/csi-driver-nfs.yaml.j2
template/templates/kubernetes/flux/repositories/helm/kustomization.yaml.j2
template/vars/addons.sample.yaml

Add csi-driver-nfs support with the following config options:
```yaml
csi_driver_nfs:
enabled: false
```

feat: add csi-driver-nfs addon

---

template/templates/addons/kubernetes-dashboard/app/helmrelease.yaml.j2
template/templates/addons/kubernetes-dashboard/ks.yaml.j2

Upgrade with the new ingress changes, insecure login changes, and disabling the subcharts for cert-manager, nginx-ingress, and metrics-server.

feat(kubernetes-dashboard): Upgrade chart to 7.0.2

---

README.md

This prevents getting rate-limited in case DNS is not working and a new nuke is needed.

Move certificate switch in README after DNS

---

README.md

this way we don't need to enable ssh for root

chore: update readme - instructions for enabling sudo

---

README.md

Added **System Requirements** section to README

add system requirements

---

README.md

For easier reference and to make room for other L2 headings such as **"Usage"** and **"FAQs"**.

bring setup steps under one L2 heading

---

bootstrap/tasks/validation/net.yaml

fix(ansible/net-valid): The external address fact.

---

.devcontainer/devcontainer.json

Fixes #1103. ~~Should we use a newer Python version though?~~ No need, discussed in issue.

Set dev container Python version to 3.10.13

---

.taskfiles/BrewTasks.yaml

bootstrap/vars/config.yaml instructs to extract cloudflare tunnel parameters using jq.

Install jq in task brew:deps

---

.github/workflows/lychee.yaml

This was recently fixed in the new v1.9.0 action

Change back to output file

---

.github/tests/addons.yaml
.github/tests/config.yaml
.github/workflows/e2e.yaml
.taskfiles/BrewTasks.yaml
.taskfiles/RepoTasks.yaml
.taskfiles/SopsTasks.yaml
README.md
Taskfile.yaml
bootstrap/configure.yaml
bootstrap/tasks/validation/cli.yaml
bootstrap/tasks/validation/cloudflare.yaml
bootstrap/tasks/validation/net.yaml

This is a quick and dirty e2e workflow test that ensures `task configure` runs successfully on PRs.

feat: attempt to add a e2e workflow

---

bootstrap/tasks/validation/github.yaml
bootstrap/templates/ansible/inventory/group_vars/kubernetes/main.yaml.j2
bootstrap/templates/kubernetes/apps/observability/kube-prometheus-stack/app/helmrelease.yaml.j2
bootstrap/templates/kubernetes/k0s/k0s-config.yaml.j2

- Add support for monitoring etcd on k0s
- Force etcd on k3s even when a single master node
- Fix logic in GH checks

feat: enable etcd monitoring for k0s

---

.taskfiles/K0s/Taskfile.yaml
bootstrap/templates/kubernetes/k0s/k0sctl.yaml.j2

- add reset hooks for cleaning up cilium
- ansible nuke playbook not needed for k0s

feat: k0s add reset hooks for cleaning up cilium

---

.devcontainer/devcontainer.json

Newest changes (Python and dependencies) broke the devcontainer environment.

Fix devcontainers environment with latest changes

---

.github/tests/config-k0s.yaml
.github/tests/config-k3s-ipv4.yaml
.github/tests/config-k3s-ipv6.yaml
.github/tests/config-k3s-no-kube-vip.yaml
.github/tests/config-talos.yaml
bootstrap/scripts/loader.py
bootstrap/scripts/validation.py
bootstrap/templates/ansible/playbooks/cluster-nuke.yaml.j2
bootstrap/templates/kubernetes/apps/storage/openebs/app/helmrelease.yaml.j2
bootstrap/templates/kubernetes/k0s/resources/hooks/reset-system.sh.j2
bootstrap/templates/partials/cilium-values-full.partial.yaml.j2
bootstrap/templates/partials/cilium-values-init.partial.yaml.j2
bootstrap/vars/config.sample.yaml
requirements.txt

Move the following vars to `bootstrap_advanced`
- Cilium LB mode
- Local path storage dir

feat: move various config options to advanced flags

---

.github/tests/addons.yaml
bootstrap/templates/kubernetes/apps/kube-system/kustomization.yaml.j2
bootstrap/templates/kubernetes/apps/kube-system/spegel/app/helmrelease.yaml.j2
bootstrap/templates/kubernetes/apps/kube-system/spegel/app/kustomization.yaml.j2
bootstrap/templates/kubernetes/apps/kube-system/spegel/ks.yaml.j2
bootstrap/templates/kubernetes/apps/storage/csi-driver-smb/app/helmrelease.yaml.j2
bootstrap/templates/kubernetes/apps/storage/csi-driver-smb/app/storageclass.yaml.j2
bootstrap/templates/kubernetes/k0s/k0sctl.yaml.j2
bootstrap/templates/kubernetes/k0s/resources/containerd/default.toml.j2
bootstrap/templates/kubernetes/k0s/resources/containerd/unprivileged-ports.toml.j2
bootstrap/templates/kubernetes/talos/talconfig.yaml.j2
bootstrap/vars/addons.sample.yaml

This moves spegel from a addon to a core component also downgrades csi smb to 1.13.0 to fix issue with k0s

feat: add spegel to core components

---

.envrc
.github/workflows/e2e.yaml
.taskfiles/Ansible/Taskfile.yaml
.taskfiles/Kubernetes/Taskfile.yaml
.taskfiles/Workstation/Taskfile.yaml
README.md
Taskfile.yaml

- Update taskfiles
- Update e2e tests and workflows
- Update readme

chore: improvements to e2e workflow

---

.devcontainer/ci/devcontainer.json
.devcontainer/ci/features/devcontainer-feature.json
.devcontainer/ci/features/install.sh
.devcontainer/postCreateCommand.sh

Switch to alpine based devcontaienr
- Faster builds
- Easier installation of tools

feat: switch devcontainer to alpine :rocket:

---

.devcontainer/ci/Dockerfile
.devcontainer/ci/devcontainer.json
.devcontainer/ci/features/devcontainer-feature.json
.devcontainer/ci/features/install.sh
.devcontainer/devcontainer.json
.github/workflows/devcontainer.yaml
.github/workflows/e2e.yaml
README.md

- Install iputils
- Update readme to include devcontainer info
- add arm64 support for devcontainer

feat: more improvements to devcontainer and arm64

---

.envrc
.github/tests/config-k0s.yaml
.github/tests/config-k3s-ipv4.yaml
.github/tests/config-k3s-ipv6.yaml
.github/tests/config-talos.yaml
.taskfiles/Talos/Taskfile.yaml
README.md
bootstrap/scripts/validation.py
bootstrap/templates/ansible/inventory/group_vars/kubernetes/main.yaml.j2
bootstrap/templates/ansible/inventory/group_vars/master/main.yaml.j2
bootstrap/templates/ansible/inventory/group_vars/worker/main.yaml.j2
bootstrap/templates/ansible/inventory/hosts.yaml.j2
bootstrap/templates/ansible/playbooks/cluster-prepare.yaml.j2
bootstrap/templates/kubernetes/k0s/k0sctl.yaml.j2
bootstrap/templates/kubernetes/talos/talconfig.yaml.j2
bootstrap/vars/config.sample.yaml

Part of https://github.com/onedr0p/flux-cluster-template/discussions/1251

fix: address talos comments

---

.devcontainer/ci/features/devcontainer-feature.json
.devcontainer/devcontainer.json
.github/tests/config-k0s.yaml
.github/tests/config-k3s-ipv4.yaml
.github/tests/config-k3s-ipv6.yaml
.github/tests/config-talos.yaml
README.md
bootstrap/templates/ansible/playbooks/cluster-prepare.yaml.j2
config.sample.yaml

Renamed repo to cluster-template

feat: rename repo to cluster-template

---

.github/tests/config-talos.yaml
.github/workflows/devcontainer.yaml
.github/workflows/e2e.yaml
.github/workflows/flux-diff.yaml
.github/workflows/kubeconform.yaml
.github/workflows/label-sync.yaml
.github/workflows/labeler.yaml
.github/workflows/lychee.yaml
.github/workflows/release.yaml
README.md
bootstrap/templates/ansible/playbooks/tasks/version-check.yaml.j2
config.sample.yaml

Add jsonschema for github workflows and update readme

fix: talos customization multiline string and ansible raw/endraw

---

.vscode/extensions.json

- Function: Shows TODO, FIXME, etc. comment tags in a tree view
- Goal: to better manage and track of remaining work
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

Update extensions.json: added Todo Tree

---

bootstrap/templates/partials/cilium-values-full.partial.yaml.j2
bootstrap/templates/partials/cilium-values-init.partial.yaml.j2

See onedr0p/cluster-template#1295

Add note about device selection in Cilium Helm Release

---

.envrc

Fix the path to the talosconfig following the refactoring in #1326.
(amended to fix commit subject)

fix(talos): Update envvar for talosconfig

---

README.md

Wrong indentation breaks the code snippet.

fix: identation fix

---

.gitignore

Just in case there's incidents. You don't want that in your commit history.

Add talosconfig to .gitignore

---

.github/renovate.json5

From single backslash to double backslash

Fix (renovate): Invalid escape character in string.

---

.taskfiles/Workstation/Brewfile

https://github.com/siderolabs/homebrew-tap#how-do-i-install-talosctl
```
brew tap siderolabs/tap
brew install talosctl
```

fix(task): siderolabs brew tap

---

bootstrap/templates/kubernetes/apps/kube-system/kubelet-csr-approver/app/helmrelease.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/apps/helmfile.yaml.j2

https://github.com/postfinance/kubelet-csr-approver/issues/253
Reverts onedr0p/cluster-template#1476

Revert "feat(helm): update chart kubelet-csr-approver to 1.2.0"

---

bootstrap/scripts/plugin.py
bootstrap/templates/kubernetes/bootstrap/talos/patches/README.md.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/controller/api-access.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/controller/cluster.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/controller/disable-admission-controller.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/controller/etcd.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/cluster-discovery.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/containerd.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/disable-search-domain.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/hostdns.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/kubelet.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/openebs-local.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/sysctl.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/talconfig.yaml.j2
config.sample.yaml

- Add a makejinja function for returning files in patches directory
- Move non-conditional patches into patches directory

feat: `talos_patches` makejinja func and move certain patches to `patches` directory

---

.taskfiles/Talos/Taskfile.yaml
README.md

Also add checks for Talos and kubernetes version

feat: change talos upgrade task to support version instead of image

---

.taskfiles/workstation/Archfile

A useful tool that might see a usecase here soon.

chore: add minijinja-cli-bin to Archfile

---

bootstrap/templates/kubernetes/apps/kube-system/cilium/app/helm-values.yaml.j2
bootstrap/templates/kubernetes/apps/kube-system/cilium/config/cilium-l3.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/dns.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/patches/global/ntp.yaml.j2
bootstrap/templates/kubernetes/bootstrap/talos/talconfig.yaml.j2
bootstrap/templates/kubernetes/flux/config/cluster.yaml.j2
config.sample.yaml

DHCP causes inconsistency and confusion, lets move forward with only having static assignments.

feat(bootstrap): static ips and default ntp/dns servers

---

bootstrap/templates/kubernetes/apps/kube-system/cilium/app/helm-values.yaml.j2
bootstrap/templates/kubernetes/apps/kube-system/coredns/app/helm-values.yaml.j2

Add hostNamespaceOnly setting

---

README.md

Commit b7273c2aaf52f4614501acd5400c81c02f2d197a moved the Kubernetes task file from `.taskfiles/Kubernetes/Taskfile.yaml` to `.taskfiles/kubernetes/Taskfile.yaml`. This PR adjusts sources to changes.

docs: update kubernetes task file reference

---

.github/workflows/e2e.yaml
README.md
mise.toml

Cut down on Github dependencies due to rate-limiting, also remove stern for the same reason as it's not required.

feat(mise): use pip instead of uv

---

templates/config/kubernetes/bootstrap/talos/talconfig.yaml.j2

Fixes issue with true/false values in secureboot

fix: update talhelper config

---

.mise.toml
.taskfiles/bootstrap/Taskfile.yaml
.taskfiles/talos/Taskfile.yaml
.taskfiles/template/Taskfile.yaml
Taskfile.yaml
scripts/bootstrap-apps.sh
templates/config/.sops.yaml.j2

- Fix issue with github deploy key not being encrypted or applied
- Updates tasks to use TALOS_DIR
- Update sops config

fix: issue with GitHub deploy key

---

templates/config/bootstrap/helmfile.yaml.j2
templates/config/kubernetes/apps/kube-system/kustomization.yaml.j2
templates/config/kubernetes/apps/kube-system/spegel/app/helm/kustomizeconfig.yaml.j2
templates/config/kubernetes/apps/kube-system/spegel/app/helm/values.yaml.j2
templates/config/kubernetes/apps/kube-system/spegel/app/helmrelease.yaml.j2
templates/config/kubernetes/apps/kube-system/spegel/app/helmrepository.yaml.j2
templates/config/kubernetes/apps/kube-system/spegel/app/kustomization.yaml.j2
templates/config/kubernetes/apps/kube-system/spegel/ks.yaml.j2
templates/scripts/plugin.py

Signed-off-by: Devin Buhl <devin@buhl.casa>

feat: only deploy spegel if more than one node

---

.github/workflows/e2e.yaml
.mise.toml
.renovaterc.json5
.taskfiles/template/Taskfile.yaml
README.md
requirements.txt
templates/scripts/plugin.py

chore: remove requirements.txt

---

scripts/bootstrap-apps.sh

update external-dns mainfest yaml filename
